//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBarProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DLjihao {
            get {
                return ((string)(this["DLjihao"]));
            }
            set {
                this["DLjihao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rKey {
            get {
                return ((string)(this["rKey"]));
            }
            set {
                this["rKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rtime {
            get {
                return ((string)(this["rtime"]));
            }
            set {
                this["rtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PFroundYL {
            get {
                return ((int)(this["PFroundYL"]));
            }
            set {
                this["PFroundYL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DLparaTong {
            get {
                return ((int)(this["DLparaTong"]));
            }
            set {
                this["DLparaTong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DLparaMin {
            get {
                return ((int)(this["DLparaMin"]));
            }
            set {
                this["DLparaMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"1,0,400,0.6,3,100,0.4,3|2,0,400,0.6,3,100,0.4,3|3,0,400,0.6,3,100,0.4,3|4,0,400,0.6,3,100,0.4,3|5,0,400,0.6,3,100,0.4,3|6,0,400,0.6,3,100,0.4,3|7,0,400,0.6,3,100,0.4,3|8,0,400,0.6,3,100,0.4,3|9,0,400,0.6,3,100,0.4,3|10,0,400,0.6,3,100,0.4,3|11,0,400,0.6,3,100,0.4,3|12,0,400,0.6,3,100,0.4,3|13,0,400,0.6,3,100,0.4,3|14,0,400,0.6,3,100,0.4,3|15,0,400,0.6,3,100,0.4,3")]
        public string DLparaDitou {
            get {
                return ((string)(this["DLparaDitou"]));
            }
            set {
                this["DLparaDitou"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2,9600,8,none,XK3190C8,100,50000,0,g,3,true,1,false,50,1000|COM3,9600,8,none,X" +
            "K3190C8,100,50000,0,g,3,true,1,false,50,1000|COM4,9600,8,none,XK3190C8,100,50000" +
            ",0,g,3,true,1,false,50,1000")]
        public string DLparaCheng {
            get {
                return ((string)(this["DLparaCheng"]));
            }
            set {
                this["DLparaCheng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1,38400,7,even,100")]
        public string DLparaPLC {
            get {
                return ((string)(this["DLparaPLC"]));
            }
            set {
                this["DLparaPLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int paraKeyB {
            get {
                return ((int)(this["paraKeyB"]));
            }
            set {
                this["paraKeyB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CLjihao {
            get {
                return ((string)(this["CLjihao"]));
            }
            set {
                this["CLjihao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2,9600,8,None,1,True,1500,1500|COM3,9600,8,None,1,True,500,500|COM4,9600,8,Non" +
            "e,1,True,500,500|COM5,9600,8,None,1,True,500,500")]
        public string CLparaCheng {
            get {
                return ((string)(this["CLparaCheng"]));
            }
            set {
                this["CLparaCheng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1,38400,7,even,100")]
        public string CLparaPLC {
            get {
                return ((string)(this["CLparaPLC"]));
            }
            set {
                this["CLparaPLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiLiao {
            get {
                return ((bool)(this["DiLiao"]));
            }
            set {
                this["DiLiao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChengLiao {
            get {
                return ((bool)(this["ChengLiao"]));
            }
            set {
                this["ChengLiao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string islogin {
            get {
                return ((string)(this["islogin"]));
            }
            set {
                this["islogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dqtime {
            get {
                return ((string)(this["dqtime"]));
            }
            set {
                this["dqtime"] = value;
            }
        }
    }
}
