using DotNetBarProject.view.custom.view;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace DotNetBarProject.ChenLiao
{
    partial class frmCL
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DataGridViewCellStyle gridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle3 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle4 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle5 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle6 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle7 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle8 = new DataGridViewCellStyle();
            DataGridViewCellStyle gridViewCellStyle9 = new DataGridViewCellStyle();
            this.panTop = new Panel();
            this.lblExit = new Label();
            this.lblDate = new Label();
            this.lblGS = new Label();
            this.lblBB = new Label();
            this.panBottom = new Panel();
            this.lblBtnSch = new Label();
            this.lblTS = new Label();
            this.lblBtnMC = new Label();
            this.panel1 = new Panel();
            this.panel8 = new Panel();
            this.panel3 = new Panel();
            this.lblTPerr = new Label();
            this.lblKeyS = new Label();
            this.lblRowCount = new Label();
            this.panel4 = new Panel();
            this.txtLDH = new Label();
            this.label4 = new Label();
            this.label6 = new Label();
            this.label8 = new Label();
            this.label5 = new Label();
            this.label3 = new Label();
            this.panel2 = new Panel();
            this.panel7 = new Panel();
            this.lblCLzl = new Label();
            this.panel12 = new Panel();
            this.label2 = new Label();
            this.lblCLwc = new Label();
            this.lblCLwd = new Label();
            this.pBarCL = new ProgressBar();
            this.panel11 = new Panel();
            this.lblCLcheng = new Label();
            this.label16 = new Label();
            this.panel6 = new Panel();
            this.lblCLmbzl = new Label();
            this.panel10 = new Panel();
            this.lblCLyc = new Label();
            this.label13 = new Label();
            this.lblCLmcpz = new Label();
            this.panel5 = new Panel();
            this.lblCLrlname = new Label();
            this.panel9 = new Panel();
            this.lblCLdh = new Label();
            this.label10 = new Label();
            this.dgvDH = new DataGridView();
            this.col1 = new DataGridViewTextBoxColumn();
            this.col2 = new DataGridViewTextBoxColumn();
            this.col3 = new DataGridViewTextBoxColumn();
            this.col4 = new DataGridViewTextBoxColumn();
            this.col5 = new DataGridViewTextBoxColumn();
            this.col6 = new DataGridViewTextBoxColumn();
            this.col7 = new DataGridViewTextBoxColumn();
            this.col8 = new DataGridViewTextBoxColumn();
            this.dgvData = new dgvEX();
            this.txtKZ = new LblTxt();
            this.txtDJ = new LblTxt();
            this.txtMS = new LblTxt();
            this.txtZL = new LblTxt();
            this.txtSL = new LblTxt();
            this.txtJH = new LblTxt();
            this.txtYS = new LblTxt();
            this.txtSH = new LblTxt();
            this.txtSZ = new LblTxt();
            this.txtKH = new LblTxt();
            this.txtDDH = new LblTxt();
            this.colBH = new DataGridViewTextBoxColumn();
            this.colGX = new DataGridViewTextBoxColumn();
            this.colRL = new DataGridViewTextBoxColumn();
            this.colYL = new DataGridViewTextBoxColumn();
            this.colDW = new DataGridViewTextBoxColumn();
            this.colCL = new DataGridViewTextBoxColumn();
            this.colCLDW = new DataGridViewTextBoxColumn();
            this.colDH = new DataGridViewTextBoxColumn();
            this.colSN = new DataGridViewTextBoxColumn();
            this.panTop.SuspendLayout();
            this.panBottom.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel8.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel7.SuspendLayout();
            this.panel12.SuspendLayout();
            this.panel11.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel10.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel9.SuspendLayout();
            this.SuspendLayout();
            this.panTop.BackColor = Color.PowderBlue;
            this.panTop.BorderStyle = BorderStyle.FixedSingle;
            this.panTop.Controls.Add((Control) this.lblExit);
            this.panTop.Controls.Add((Control) this.lblDate);
            this.panTop.Controls.Add((Control) this.lblGS);
            this.panTop.Controls.Add((Control) this.lblBB);
            this.panTop.Dock = DockStyle.Top;
            this.panTop.Location = new Point(3, 3);
            this.panTop.Name = "panTop";
            this.panTop.Size = new Size(1016, 52);
            this.panTop.TabIndex = 1;
            this.lblExit.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblExit.Location = new Point(962, 0);
            this.lblExit.Name = "lblExit";
            this.lblExit.Size = new Size(50, 50);
            this.lblExit.TabIndex = 27;
            this.lblExit.Text = "●";
            this.lblExit.TextAlign = ContentAlignment.MiddleCenter;
            this.lblExit.MouseClick += new MouseEventHandler(this.lblExit_MouseClick);
            this.lblDate.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblDate.AutoSize = true;
            this.lblDate.Font = new Font("黑体", 14f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblDate.Location = new Point(687, 17);
            this.lblDate.Name = "lblDate";
            this.lblDate.Size = new Size(248, 19);
            this.lblDate.TabIndex = 23;
            this.lblDate.Text = "2016年8月19日 10:14:30";
            this.lblGS.AutoSize = true;
            this.lblGS.Font = new Font("黑体", 18f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
            this.lblGS.ForeColor = Color.DarkRed;
            this.lblGS.Location = new Point(9, 12);
            this.lblGS.Name = "lblGS";
            this.lblGS.Size = new Size(160, 24);
            this.lblGS.TabIndex = 0;
            this.lblGS.Text = "称料控制系统";
            this.lblBB.AutoSize = true;
            this.lblBB.Location = new Point(419, 37);
            this.lblBB.Name = "lblBB";
            this.lblBB.Size = new Size(29, 12);
            this.lblBB.TabIndex = 25;
            this.lblBB.Text = "Ver:";
            this.panBottom.Controls.Add((Control) this.lblBtnSch);
            this.panBottom.Controls.Add((Control) this.lblTS);
            this.panBottom.Controls.Add((Control) this.lblBtnMC);
            this.panBottom.Controls.Add((Control) this.dgvDH);
            this.panBottom.Dock = DockStyle.Bottom;
            this.panBottom.Location = new Point(3, 543);
            this.panBottom.Name = "panBottom";
            this.panBottom.Padding = new Padding(3);
            this.panBottom.Size = new Size(1016, 220);
            this.panBottom.TabIndex = 0;
            this.lblBtnSch.BackColor = Color.DarkCyan;
            this.lblBtnSch.BorderStyle = BorderStyle.FixedSingle;
            this.lblBtnSch.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblBtnSch.Location = new Point(7, 2);
            this.lblBtnSch.Name = "lblBtnSch";
            this.lblBtnSch.Size = new Size(136, 39);
            this.lblBtnSch.TabIndex = 0;
            this.lblBtnSch.Text = "查询料单( • )";
            this.lblBtnSch.TextAlign = ContentAlignment.MiddleCenter;
            this.lblTS.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.lblTS.BackColor = Color.Gold;
            this.lblTS.BorderStyle = BorderStyle.FixedSingle;
            this.lblTS.Font = new Font("黑体", 18f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblTS.ForeColor = Color.DarkRed;
            this.lblTS.ImageAlign = ContentAlignment.TopLeft;
            this.lblTS.Location = new Point(149, 2);
            this.lblTS.Name = "lblTS";
            this.lblTS.Size = new Size(722, 39);
            this.lblTS.TabIndex = 5;
            this.lblTS.Text = "“上翻/下翻”选择染助剂,“确认”开始称料(放好料桶)！";
            this.lblTS.TextAlign = ContentAlignment.MiddleCenter;
            this.lblBtnMC.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblBtnMC.BackColor = Color.DarkCyan;
            this.lblBtnMC.BorderStyle = BorderStyle.FixedSingle;
            this.lblBtnMC.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblBtnMC.Location = new Point(877, 2);
            this.lblBtnMC.Name = "lblBtnMC";
            this.lblBtnMC.Size = new Size(131, 39);
            this.lblBtnMC.TabIndex = 4;
            this.lblBtnMC.Text = "免称扣除(上翻)";
            this.lblBtnMC.TextAlign = ContentAlignment.MiddleCenter;
            this.panel1.Controls.Add((Control) this.panel8);
            this.panel1.Controls.Add((Control) this.panel2);
            this.panel1.Dock = DockStyle.Fill;
            this.panel1.Location = new Point(3, 55);
            this.panel1.Name = "panel1";
            this.panel1.Padding = new Padding(3);
            this.panel1.Size = new Size(1016, 488);
            this.panel1.TabIndex = 0;
            this.panel8.Controls.Add((Control) this.dgvData);
            this.panel8.Controls.Add((Control) this.panel3);
            this.panel8.Controls.Add((Control) this.panel4);
            this.panel8.Dock = DockStyle.Fill;
            this.panel8.Location = new Point(3, 3);
            this.panel8.Name = "panel8";
            this.panel8.Padding = new Padding(3);
            this.panel8.Size = new Size(705, 482);
            this.panel8.TabIndex = 0;
            this.panel3.BorderStyle = BorderStyle.FixedSingle;
            this.panel3.Controls.Add((Control) this.lblTPerr);
            this.panel3.Controls.Add((Control) this.lblKeyS);
            this.panel3.Controls.Add((Control) this.lblRowCount);
            this.panel3.Dock = DockStyle.Bottom;
            this.panel3.Location = new Point(3, 449);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(699, 30);
            this.panel3.TabIndex = 4;
            this.lblTPerr.AutoSize = true;
            this.lblTPerr.Location = new Point(-1, 17);
            this.lblTPerr.Name = "lblTPerr";
            this.lblTPerr.Size = new Size(11, 12);
            this.lblTPerr.TabIndex = 33;
            this.lblTPerr.Text = "0";
            this.lblKeyS.AutoSize = true;
            this.lblKeyS.Location = new Point(13, 17);
            this.lblKeyS.Name = "lblKeyS";
            this.lblKeyS.Size = new Size(11, 12);
            this.lblKeyS.TabIndex = 31;
            this.lblKeyS.Text = "0";
            this.lblRowCount.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblRowCount.AutoSize = true;
            this.lblRowCount.Font = new Font("宋体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblRowCount.Location = new Point(505, 6);
            this.lblRowCount.Name = "lblRowCount";
            this.lblRowCount.Size = new Size(171, 16);
            this.lblRowCount.TabIndex = 0;
            this.lblRowCount.Text = "本料单共有 ? 条染料";
            this.panel4.BorderStyle = BorderStyle.FixedSingle;
            this.panel4.Controls.Add((Control) this.txtLDH);
            this.panel4.Controls.Add((Control) this.label4);
            this.panel4.Controls.Add((Control) this.txtKZ);
            this.panel4.Controls.Add((Control) this.txtDJ);
            this.panel4.Controls.Add((Control) this.txtMS);
            this.panel4.Controls.Add((Control) this.label6);
            this.panel4.Controls.Add((Control) this.label8);
            this.panel4.Controls.Add((Control) this.txtZL);
            this.panel4.Controls.Add((Control) this.txtSL);
            this.panel4.Controls.Add((Control) this.txtJH);
            this.panel4.Controls.Add((Control) this.txtYS);
            this.panel4.Controls.Add((Control) this.txtSH);
            this.panel4.Controls.Add((Control) this.txtSZ);
            this.panel4.Controls.Add((Control) this.txtKH);
            this.panel4.Controls.Add((Control) this.txtDDH);
            this.panel4.Controls.Add((Control) this.label5);
            this.panel4.Controls.Add((Control) this.label3);
            this.panel4.Dock = DockStyle.Top;
            this.panel4.Location = new Point(3, 3);
            this.panel4.Name = "panel4";
            this.panel4.Size = new Size(699, 113);
            this.panel4.TabIndex = 0;
            this.txtLDH.AutoSize = true;
            this.txtLDH.Font = new Font("黑体", 20f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtLDH.ForeColor = Color.DarkRed;
            this.txtLDH.Location = new Point(58, 14);
            this.txtLDH.Name = "txtLDH";
            this.txtLDH.Size = new Size(177, 27);
            this.txtLDH.TabIndex = 54;
            this.txtLDH.Text = "81808000011";
            this.label4.AutoSize = true;
            this.label4.Font = new Font("宋体", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label4.Location = new Point(16, 22);
            this.label4.Name = "label4";
            this.label4.Size = new Size(45, 14);
            this.label4.TabIndex = 70;
            this.label4.Text = "单号:";
            this.label6.AutoSize = true;
            this.label6.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label6.Location = new Point(652, 67);
            this.label6.Name = "label6";
            this.label6.Size = new Size(19, 12);
            this.label6.TabIndex = 67;
            this.label6.Text = "Kg";
            this.label8.AutoSize = true;
            this.label8.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label8.Location = new Point(652, 93);
            this.label8.Name = "label8";
            this.label8.Size = new Size(19, 12);
            this.label8.TabIndex = 66;
            this.label8.Text = "Kg";
            this.label5.AutoSize = true;
            this.label5.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label5.Location = new Point(365, 86);
            this.label5.Name = "label5";
            this.label5.Size = new Size(16, 15);
            this.label5.TabIndex = 68;
            this.label5.Text = "m";
            this.label3.AutoSize = true;
            this.label3.Font = new Font("宋体", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label3.Location = new Point(649, 9);
            this.label3.Name = "label3";
            this.label3.Size = new Size(31, 14);
            this.label3.TabIndex = 69;
            this.label3.Text = "g/m";
            this.panel2.Controls.Add((Control) this.panel7);
            this.panel2.Controls.Add((Control) this.panel6);
            this.panel2.Controls.Add((Control) this.panel5);
            this.panel2.Dock = DockStyle.Right;
            this.panel2.Location = new Point(708, 3);
            this.panel2.Name = "panel2";
            this.panel2.Padding = new Padding(4);
            this.panel2.Size = new Size(305, 482);
            this.panel2.TabIndex = 0;
            this.panel7.BorderStyle = BorderStyle.FixedSingle;
            this.panel7.Controls.Add((Control) this.lblCLzl);
            this.panel7.Controls.Add((Control) this.panel12);
            this.panel7.Controls.Add((Control) this.panel11);
            this.panel7.Dock = DockStyle.Fill;
            this.panel7.Location = new Point(4, 264);
            this.panel7.Name = "panel7";
            this.panel7.Size = new Size(297, 214);
            this.panel7.TabIndex = 2;
            this.lblCLzl.BackColor = SystemColors.Window;
            this.lblCLzl.Dock = DockStyle.Fill;
            this.lblCLzl.Font = new Font("黑体", 35.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLzl.ForeColor = Color.DarkRed;
            this.lblCLzl.Location = new Point(0, 35);
            this.lblCLzl.Name = "lblCLzl";
            this.lblCLzl.Size = new Size(295, 97);
            this.lblCLzl.TabIndex = 7;
            this.lblCLzl.Text = "2000.0000克";
            this.lblCLzl.TextAlign = ContentAlignment.MiddleRight;
            this.panel12.BackColor = Color.White;
            this.panel12.Controls.Add((Control) this.label2);
            this.panel12.Controls.Add((Control) this.lblCLwc);
            this.panel12.Controls.Add((Control) this.lblCLwd);
            this.panel12.Controls.Add((Control) this.pBarCL);
            this.panel12.Dock = DockStyle.Bottom;
            this.panel12.Location = new Point(0, 132);
            this.panel12.Name = "panel12";
            this.panel12.Size = new Size(295, 80);
            this.panel12.TabIndex = 6;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.label2.ForeColor = Color.Black;
            this.label2.Location = new Point(6, 31);
            this.label2.Name = "label2";
            this.label2.Size = new Size(51, 16);
            this.label2.TabIndex = 8;
            this.label2.Text = "误差:";
            this.label2.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCLwc.AutoSize = true;
            this.lblCLwc.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLwc.ForeColor = Color.DarkRed;
            this.lblCLwc.Location = new Point(54, 31);
            this.lblCLwc.Name = "lblCLwc";
            this.lblCLwc.Size = new Size(79, 16);
            this.lblCLwc.TabIndex = 6;
            this.lblCLwc.Text = "-10000克";
            this.lblCLwc.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCLwd.Dock = DockStyle.Top;
            this.lblCLwd.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLwd.ForeColor = Color.Green;
            this.lblCLwd.Location = new Point(0, 0);
            this.lblCLwd.Name = "lblCLwd";
            this.lblCLwd.Size = new Size(295, 25);
            this.lblCLwd.TabIndex = 7;
            this.lblCLwd.Text = "稳定";
            this.lblCLwd.TextAlign = ContentAlignment.MiddleRight;
            this.pBarCL.Dock = DockStyle.Bottom;
            this.pBarCL.Location = new Point(0, 50);
            this.pBarCL.Name = "pBarCL";
            this.pBarCL.Size = new Size(295, 30);
            this.pBarCL.Style = ProgressBarStyle.Continuous;
            this.pBarCL.TabIndex = 5;
            this.pBarCL.Value = 50;
            this.panel11.BackColor = Color.PaleTurquoise;
            this.panel11.BorderStyle = BorderStyle.FixedSingle;
            this.panel11.Controls.Add((Control) this.lblCLcheng);
            this.panel11.Controls.Add((Control) this.label16);
            this.panel11.Dock = DockStyle.Top;
            this.panel11.Location = new Point(0, 0);
            this.panel11.Name = "panel11";
            this.panel11.Size = new Size(295, 35);
            this.panel11.TabIndex = 4;
            this.lblCLcheng.AutoSize = true;
            this.lblCLcheng.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLcheng.Location = new Point(96, 7);
            this.lblCLcheng.Name = "lblCLcheng";
            this.lblCLcheng.Size = new Size(106, 20);
            this.lblCLcheng.TabIndex = 2;
            this.lblCLcheng.Text = "( ? 号称)";
            this.label16.AutoSize = true;
            this.label16.BackColor = Color.Transparent;
            this.label16.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
            this.label16.ForeColor = Color.DarkRed;
            this.label16.Location = new Point(4, 6);
            this.label16.Name = "label16";
            this.label16.Size = new Size(93, 20);
            this.label16.TabIndex = 0;
            this.label16.Text = "实际重量";
            this.label16.TextAlign = ContentAlignment.MiddleLeft;
            this.panel6.BorderStyle = BorderStyle.FixedSingle;
            this.panel6.Controls.Add((Control) this.lblCLmbzl);
            this.panel6.Controls.Add((Control) this.panel10);
            this.panel6.Controls.Add((Control) this.lblCLmcpz);
            this.panel6.Dock = DockStyle.Top;
            this.panel6.Location = new Point(4, 134);
            this.panel6.Name = "panel6";
            this.panel6.Size = new Size(297, 130);
            this.panel6.TabIndex = 1;
            this.lblCLmbzl.BackColor = SystemColors.Window;
            this.lblCLmbzl.Dock = DockStyle.Fill;
            this.lblCLmbzl.Font = new Font("黑体", 35.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLmbzl.Location = new Point(0, 35);
            this.lblCLmbzl.Name = "lblCLmbzl";
            this.lblCLmbzl.Size = new Size(295, 68);
            this.lblCLmbzl.TabIndex = 2;
            this.lblCLmbzl.Text = "2000.0000克";
            this.lblCLmbzl.TextAlign = ContentAlignment.BottomRight;
            this.panel10.BackColor = Color.PaleTurquoise;
            this.panel10.BorderStyle = BorderStyle.FixedSingle;
            this.panel10.Controls.Add((Control) this.lblCLyc);
            this.panel10.Controls.Add((Control) this.label13);
            this.panel10.Dock = DockStyle.Top;
            this.panel10.Location = new Point(0, 0);
            this.panel10.Name = "panel10";
            this.panel10.Size = new Size(295, 35);
            this.panel10.TabIndex = 3;
            this.lblCLyc.AutoSize = true;
            this.lblCLyc.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLyc.Location = new Point(96, 7);
            this.lblCLyc.Name = "lblCLyc";
            this.lblCLyc.Size = new Size(170, 20);
            this.lblCLyc.TabIndex = 2;
            this.lblCLyc.Text = "(允差 ±0.02克)";
            this.label13.AutoSize = true;
            this.label13.BackColor = Color.Transparent;
            this.label13.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
            this.label13.ForeColor = Color.DarkRed;
            this.label13.Location = new Point(4, 6);
            this.label13.Name = "label13";
            this.label13.Size = new Size(93, 20);
            this.label13.TabIndex = 0;
            this.label13.Text = "目标重量";
            this.label13.TextAlign = ContentAlignment.MiddleLeft;
            this.lblCLmcpz.BackColor = SystemColors.Window;
            this.lblCLmcpz.Dock = DockStyle.Bottom;
            this.lblCLmcpz.Font = new Font("黑体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLmcpz.ForeColor = Color.DarkRed;
            this.lblCLmcpz.Location = new Point(0, 103);
            this.lblCLmcpz.Name = "lblCLmcpz";
            this.lblCLmcpz.Size = new Size(295, 25);
            this.lblCLmcpz.TabIndex = 7;
            this.lblCLmcpz.Text = "(扣除免称25000)(增加皮重1000)";
            this.lblCLmcpz.TextAlign = ContentAlignment.MiddleRight;
            this.panel5.BorderStyle = BorderStyle.FixedSingle;
            this.panel5.Controls.Add((Control) this.lblCLrlname);
            this.panel5.Controls.Add((Control) this.panel9);
            this.panel5.Dock = DockStyle.Top;
            this.panel5.Location = new Point(4, 4);
            this.panel5.Name = "panel5";
            this.panel5.Size = new Size(297, 130);
            this.panel5.TabIndex = 0;
            this.lblCLrlname.BackColor = SystemColors.Window;
            this.lblCLrlname.Dock = DockStyle.Fill;
            this.lblCLrlname.Font = new Font("宋体", 21.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLrlname.Location = new Point(0, 35);
            this.lblCLrlname.Name = "lblCLrlname";
            this.lblCLrlname.Size = new Size(295, 93);
            this.lblCLrlname.TabIndex = 1;
            this.lblCLrlname.Text = "染料名称";
            this.lblCLrlname.TextAlign = ContentAlignment.MiddleLeft;
            this.panel9.BackColor = Color.PaleTurquoise;
            this.panel9.BorderStyle = BorderStyle.FixedSingle;
            this.panel9.Controls.Add((Control) this.lblCLdh);
            this.panel9.Controls.Add((Control) this.label10);
            this.panel9.Dock = DockStyle.Top;
            this.panel9.Location = new Point(0, 0);
            this.panel9.Name = "panel9";
            this.panel9.Size = new Size(295, 35);
            this.panel9.TabIndex = 2;
            this.lblCLdh.AutoSize = true;
            this.lblCLdh.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.lblCLdh.Location = new Point(121, 7);
            this.lblCLdh.Name = "lblCLdh";
            this.lblCLdh.Size = new Size(94, 20);
            this.lblCLdh.TabIndex = 1;
            this.lblCLdh.Text = "(几号灯)";
            this.label10.AutoSize = true;
            this.label10.BackColor = Color.Transparent;
            this.label10.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
            this.label10.ForeColor = Color.DarkRed;
            this.label10.Location = new Point(4, 6);
            this.label10.Name = "label10";
            this.label10.Size = new Size(114, 20);
            this.label10.TabIndex = 0;
            this.label10.Text = "染化料名称";
            this.label10.TextAlign = ContentAlignment.MiddleLeft;
            this.dgvDH.AllowUserToAddRows = false;
            this.dgvDH.AllowUserToDeleteRows = false;
            this.dgvDH.AllowUserToResizeColumns = false;
            this.dgvDH.AllowUserToResizeRows = false;
            this.dgvDH.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDH.ColumnHeadersVisible = false;
            this.dgvDH.Columns.AddRange((DataGridViewColumn) this.col1, (DataGridViewColumn) this.col2, (DataGridViewColumn) this.col3, (DataGridViewColumn) this.col4, (DataGridViewColumn) this.col5, (DataGridViewColumn) this.col6, (DataGridViewColumn) this.col7, (DataGridViewColumn) this.col8);
            gridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleLeft;
            gridViewCellStyle1.BackColor = Color.LightGray;
            gridViewCellStyle1.Font = new Font("宋体", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            gridViewCellStyle1.ForeColor = SystemColors.ControlText;
            gridViewCellStyle1.SelectionBackColor = SystemColors.Window;
            gridViewCellStyle1.SelectionForeColor = SystemColors.ControlText;
            gridViewCellStyle1.WrapMode = DataGridViewTriState.False;
            this.dgvDH.DefaultCellStyle = gridViewCellStyle1;
            this.dgvDH.Dock = DockStyle.Bottom;
            this.dgvDH.Enabled = false;
            this.dgvDH.Location = new Point(3, 44);
            this.dgvDH.MultiSelect = false;
            this.dgvDH.Name = "dgvDH";
            this.dgvDH.ReadOnly = true;
            this.dgvDH.RowHeadersVisible = false;
            this.dgvDH.RowTemplate.Height = 28;
            this.dgvDH.ScrollBars = ScrollBars.None;
            this.dgvDH.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgvDH.Size = new Size(1010, 173);
            this.dgvDH.TabIndex = 6;
            this.col1.HeaderText = "col1";
            this.col1.Name = "col1";
            this.col1.ReadOnly = true;
            this.col2.HeaderText = "col2";
            this.col2.Name = "col2";
            this.col2.ReadOnly = true;
            this.col3.HeaderText = "col3";
            this.col3.Name = "col3";
            this.col3.ReadOnly = true;
            this.col4.HeaderText = "col4";
            this.col4.Name = "col4";
            this.col4.ReadOnly = true;
            this.col5.HeaderText = "col5";
            this.col5.Name = "col5";
            this.col5.ReadOnly = true;
            this.col6.HeaderText = "col6";
            this.col6.Name = "col6";
            this.col6.ReadOnly = true;
            this.col7.HeaderText = "col7";
            this.col7.Name = "col7";
            this.col7.ReadOnly = true;
            this.col8.HeaderText = "col8";
            this.col8.Name = "col8";
            this.col8.ReadOnly = true;
            this.dgvData.AllowUserToAddRows = false;
            this.dgvData.AllowUserToDeleteRows = false;
            this.dgvData.AllowUserToOrderColumns = true;
            this.dgvData.AllowUserToResizeColumns = false;
            this.dgvData.AllowUserToResizeRows = false;
            gridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleCenter;
            gridViewCellStyle2.BackColor = SystemColors.Control;
            gridViewCellStyle2.Font = new Font("宋体", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            gridViewCellStyle2.ForeColor = SystemColors.WindowText;
            gridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
            gridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
            gridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            this.dgvData.ColumnHeadersDefaultCellStyle = gridViewCellStyle2;
            this.dgvData.ColumnHeadersHeight = 30;
            this.dgvData.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvData.Columns.AddRange((DataGridViewColumn) this.colBH, (DataGridViewColumn) this.colGX, (DataGridViewColumn) this.colRL, (DataGridViewColumn) this.colYL, (DataGridViewColumn) this.colDW, (DataGridViewColumn) this.colCL, (DataGridViewColumn) this.colCLDW, (DataGridViewColumn) this.colDH, (DataGridViewColumn) this.colSN);
            gridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            gridViewCellStyle3.BackColor = SystemColors.Window;
            gridViewCellStyle3.Font = new Font("宋体", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            gridViewCellStyle3.ForeColor = SystemColors.ControlText;
            gridViewCellStyle3.SelectionBackColor = SystemColors.Highlight;
            gridViewCellStyle3.SelectionForeColor = SystemColors.HighlightText;
            gridViewCellStyle3.WrapMode = DataGridViewTriState.True;
            this.dgvData.DefaultCellStyle = gridViewCellStyle3;
            this.dgvData.Dock = DockStyle.Fill;
            this.dgvData.Enabled = false;
            this.dgvData.Location = new Point(3, 116);
            this.dgvData.Name = "dgvData";
            this.dgvData.ReadOnly = true;
            this.dgvData.RowHeadersVisible = false;
            this.dgvData.RowHeadersWidth = 35;
            this.dgvData.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dgvData.RowNumShow = false;
            this.dgvData.RowTemplate.Height = 30;
            this.dgvData.ScrollBars = ScrollBars.None;
            this.dgvData.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvData.ShowCellToolTips = false;
            this.dgvData.ShowEditingIcon = false;
            this.dgvData.Size = new Size(699, 333);
            this.dgvData.TabIndex = 5;
            this.txtKZ.jiange = 0;
            this.txtKZ.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtKZ.lblText = "克重";
            this.txtKZ.Location = new Point(554, 4);
            this.txtKZ.Name = "txtKZ";
            this.txtKZ.ReadOnly = true;
            this.txtKZ.Size = new Size(96, 25);
            this.txtKZ.TabIndex = 62;
            this.txtKZ.txtBackColor = SystemColors.Window;
            this.txtKZ.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtKZ.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtKZ.txtISid = false;
            this.txtKZ.txtISint = false;
            this.txtKZ.txtISmoney = false;
            this.txtKZ.txtLen = 50;
            this.txtKZ.txtMulLine = false;
            this.txtKZ.txtTop = true;
            this.txtKZ.txtUpper = false;
            this.txtKZ.upperZero = false;
            this.txtDJ.jiange = 0;
            this.txtDJ.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtDJ.lblText = "匹数";
            this.txtDJ.Location = new Point(411, 81);
            this.txtDJ.Name = "txtDJ";
            this.txtDJ.ReadOnly = true;
            this.txtDJ.Size = new Size(95, 25);
            this.txtDJ.TabIndex = 61;
            this.txtDJ.txtBackColor = SystemColors.Window;
            this.txtDJ.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtDJ.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtDJ.txtISid = false;
            this.txtDJ.txtISint = false;
            this.txtDJ.txtISmoney = false;
            this.txtDJ.txtLen = 50;
            this.txtDJ.txtMulLine = false;
            this.txtDJ.txtTop = true;
            this.txtDJ.txtUpper = false;
            this.txtDJ.upperZero = false;
            this.txtMS.jiange = 0;
            this.txtMS.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtMS.lblText = "米数";
            this.txtMS.Location = new Point(278, 81);
            this.txtMS.Name = "txtMS";
            this.txtMS.ReadOnly = true;
            this.txtMS.Size = new Size(88, 25);
            this.txtMS.TabIndex = 60;
            this.txtMS.txtBackColor = SystemColors.Window;
            this.txtMS.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtMS.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtMS.txtISid = false;
            this.txtMS.txtISint = false;
            this.txtMS.txtISmoney = false;
            this.txtMS.txtLen = 50;
            this.txtMS.txtMulLine = false;
            this.txtMS.txtTop = true;
            this.txtMS.txtUpper = false;
            this.txtMS.upperZero = false;
            this.txtZL.jiange = 0;
            this.txtZL.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtZL.lblText = "重量";
            this.txtZL.Location = new Point(554, 82);
            this.txtZL.Name = "txtZL";
            this.txtZL.ReadOnly = true;
            this.txtZL.Size = new Size(96, 25);
            this.txtZL.TabIndex = 65;
            this.txtZL.txtBackColor = SystemColors.Window;
            this.txtZL.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtZL.txtFont = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtZL.txtISid = false;
            this.txtZL.txtISint = false;
            this.txtZL.txtISmoney = true;
            this.txtZL.txtLen = 10;
            this.txtZL.txtMulLine = false;
            this.txtZL.txtTop = true;
            this.txtZL.txtUpper = false;
            this.txtZL.upperZero = false;
            this.txtSL.jiange = 0;
            this.txtSL.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtSL.lblText = "浴量";
            this.txtSL.Location = new Point(554, 56);
            this.txtSL.Name = "txtSL";
            this.txtSL.ReadOnly = true;
            this.txtSL.Size = new Size(96, 25);
            this.txtSL.TabIndex = 64;
            this.txtSL.txtBackColor = SystemColors.Window;
            this.txtSL.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtSL.txtFont = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtSL.txtISid = false;
            this.txtSL.txtISint = false;
            this.txtSL.txtISmoney = true;
            this.txtSL.txtLen = 10;
            this.txtSL.txtMulLine = false;
            this.txtSL.txtTop = true;
            this.txtSL.txtUpper = false;
            this.txtSL.upperZero = false;
            this.txtJH.jiange = 0;
            this.txtJH.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtJH.lblText = "机号";
            this.txtJH.Location = new Point(554, 30);
            this.txtJH.Name = "txtJH";
            this.txtJH.ReadOnly = true;
            this.txtJH.Size = new Size(96, 25);
            this.txtJH.TabIndex = 63;
            this.txtJH.txtBackColor = SystemColors.Window;
            this.txtJH.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtJH.txtFont = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtJH.txtISid = false;
            this.txtJH.txtISint = true;
            this.txtJH.txtISmoney = false;
            this.txtJH.txtLen = 3;
            this.txtJH.txtMulLine = false;
            this.txtJH.txtTop = true;
            this.txtJH.txtUpper = false;
            this.txtJH.upperZero = false;
            this.txtYS.jiange = 0;
            this.txtYS.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtYS.lblText = "颜色";
            this.txtYS.Location = new Point(278, 55);
            this.txtYS.Name = "txtYS";
            this.txtYS.ReadOnly = true;
            this.txtYS.Size = new Size(228, 25);
            this.txtYS.TabIndex = 59;
            this.txtYS.txtBackColor = SystemColors.Window;
            this.txtYS.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtYS.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtYS.txtISid = false;
            this.txtYS.txtISint = false;
            this.txtYS.txtISmoney = false;
            this.txtYS.txtLen = 50;
            this.txtYS.txtMulLine = false;
            this.txtYS.txtTop = true;
            this.txtYS.txtUpper = false;
            this.txtYS.upperZero = false;
            this.txtSH.jiange = 0;
            this.txtSH.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtSH.lblText = "色号";
            this.txtSH.Location = new Point(278, 29);
            this.txtSH.Name = "txtSH";
            this.txtSH.ReadOnly = true;
            this.txtSH.Size = new Size(228, 25);
            this.txtSH.TabIndex = 58;
            this.txtSH.txtBackColor = SystemColors.Window;
            this.txtSH.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtSH.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtSH.txtISid = false;
            this.txtSH.txtISint = false;
            this.txtSH.txtISmoney = false;
            this.txtSH.txtLen = 50;
            this.txtSH.txtMulLine = false;
            this.txtSH.txtTop = true;
            this.txtSH.txtUpper = false;
            this.txtSH.upperZero = false;
            this.txtSZ.jiange = 0;
            this.txtSZ.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtSZ.lblText = "品名";
            this.txtSZ.Location = new Point(21, 78);
            this.txtSZ.Name = "txtSZ";
            this.txtSZ.ReadOnly = true;
            this.txtSZ.Size = new Size(222, 25);
            this.txtSZ.TabIndex = 56;
            this.txtSZ.txtBackColor = SystemColors.Window;
            this.txtSZ.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtSZ.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtSZ.txtISid = false;
            this.txtSZ.txtISint = false;
            this.txtSZ.txtISmoney = false;
            this.txtSZ.txtLen = 50;
            this.txtSZ.txtMulLine = false;
            this.txtSZ.txtTop = true;
            this.txtSZ.txtUpper = false;
            this.txtSZ.upperZero = false;
            this.txtKH.jiange = 0;
            this.txtKH.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtKH.lblText = "客户";
            this.txtKH.Location = new Point(21, 49);
            this.txtKH.Name = "txtKH";
            this.txtKH.ReadOnly = true;
            this.txtKH.Size = new Size(222, 25);
            this.txtKH.TabIndex = 55;
            this.txtKH.txtBackColor = SystemColors.Window;
            this.txtKH.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtKH.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtKH.txtISid = false;
            this.txtKH.txtISint = false;
            this.txtKH.txtISmoney = false;
            this.txtKH.txtLen = 50;
            this.txtKH.txtMulLine = false;
            this.txtKH.txtTop = true;
            this.txtKH.txtUpper = false;
            this.txtKH.upperZero = false;
            this.txtDDH.jiange = 0;
            this.txtDDH.lblFont = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            this.txtDDH.lblText = "流程卡号";
            this.txtDDH.Location = new Point(252, 3);
            this.txtDDH.Name = "txtDDH";
            this.txtDDH.ReadOnly = true;
            this.txtDDH.Size = new Size(254, 25);
            this.txtDDH.TabIndex = 57;
            this.txtDDH.txtBackColor = SystemColors.Window;
            this.txtDDH.txtBorderStyle = BorderStyle.FixedSingle;
            this.txtDDH.txtFont = new Font("宋体", 11f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
            this.txtDDH.txtISid = false;
            this.txtDDH.txtISint = false;
            this.txtDDH.txtISmoney = false;
            this.txtDDH.txtLen = 50;
            this.txtDDH.txtMulLine = false;
            this.txtDDH.txtTop = true;
            this.txtDDH.txtUpper = false;
            this.txtDDH.upperZero = false;
            gridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleCenter;
            gridViewCellStyle4.ForeColor = Color.DarkRed;
            this.colBH.DefaultCellStyle = gridViewCellStyle4;
            this.colBH.HeaderText = "序号";
            this.colBH.Name = "colBH";
            this.colBH.ReadOnly = true;
            this.colBH.Width = 50;
            this.colGX.HeaderText = "工序";
            this.colGX.Name = "colGX";
            this.colGX.ReadOnly = true;
            this.colRL.HeaderText = "染料助剂名称";
            this.colRL.Name = "colRL";
            this.colRL.ReadOnly = true;
            this.colRL.Width = 150;
            gridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleCenter;
            gridViewCellStyle5.Font = new Font("宋体", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 134);
            gridViewCellStyle5.ForeColor = Color.DarkRed;
            gridViewCellStyle5.Format = "0.####;-0.####;\"\"";
            this.colYL.DefaultCellStyle = gridViewCellStyle5;
            this.colYL.HeaderText = "用量";
            this.colYL.Name = "colYL";
            this.colYL.ReadOnly = true;
            this.colYL.Width = 120;
            gridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.colDW.DefaultCellStyle = gridViewCellStyle6;
            this.colDW.HeaderText = "";
            this.colDW.Name = "colDW";
            this.colDW.ReadOnly = true;
            this.colDW.Width = 40;
            this.colCL.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            gridViewCellStyle7.Alignment = DataGridViewContentAlignment.MiddleCenter;
            gridViewCellStyle7.ForeColor = Color.DarkRed;
            gridViewCellStyle7.Format = "0.####;-0.####;\"\"";
            this.colCL.DefaultCellStyle = gridViewCellStyle7;
            this.colCL.HeaderText = "已存称重";
            this.colCL.Name = "colCL";
            this.colCL.ReadOnly = true;
            gridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.colCLDW.DefaultCellStyle = gridViewCellStyle8;
            this.colCLDW.HeaderText = "";
            this.colCLDW.Name = "colCLDW";
            this.colCLDW.ReadOnly = true;
            this.colCLDW.Width = 40;
            gridViewCellStyle9.Alignment = DataGridViewContentAlignment.MiddleCenter;
            gridViewCellStyle9.Format = "0;-0;\"\"";
            this.colDH.DefaultCellStyle = gridViewCellStyle9;
            this.colDH.HeaderText = "灯号";
            this.colDH.Name = "colDH";
            this.colDH.ReadOnly = true;
            this.colDH.Width = 50;
            this.colSN.HeaderText = "SN";
            this.colSN.Name = "colSN";
            this.colSN.ReadOnly = true;
            this.colSN.Visible = false;
            this.AutoScaleDimensions = new SizeF(6f, 12f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.Silver;
            this.ClientSize = new Size(1022, 766);
            this.ControlBox = false;
            this.Controls.Add((Control) this.panel1);
            this.Controls.Add((Control) this.panBottom);
            this.Controls.Add((Control) this.panTop);
            this.FormBorderStyle = FormBorderStyle.FixedSingle;
            this.KeyPreview = true;
            this.Padding = new Padding(3);
            this.ShowInTaskbar = false;
            this.StartPosition = FormStartPosition.CenterScreen;
            this.WindowState = FormWindowState.Maximized;
            this.FormClosed += new FormClosedEventHandler(this.this_FormClosed);
            this.Load += new EventHandler(this.this_Load);
            this.Shown += new EventHandler(this.this_Shown);
            this.panTop.ResumeLayout(false);
            this.panTop.PerformLayout();
            this.panBottom.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel8.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel7.ResumeLayout(false);
            this.panel12.ResumeLayout(false);
            this.panel12.PerformLayout();
            this.panel11.ResumeLayout(false);
            this.panel11.PerformLayout();
            this.panel6.ResumeLayout(false);
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.panel5.ResumeLayout(false);
            this.panel9.ResumeLayout(false);
            this.panel9.PerformLayout();
            this.ResumeLayout(false);
        }

        #endregion
        private Panel panTop;
        private Label lblGS;
        private Label lblDate;
        private Panel panBottom;
        private Panel panel1;
        private Panel panel2;
        private Label lblBtnSch;
        private Panel panel5;
        private Label label10;
        private Panel panel7;
        private Panel panel6;
        private Label lblBtnMC;
        private Panel panel8;
        private Panel panel3;
        private Label lblRowCount;
        private Panel panel4;
        private Label lblTS;
        private dgvEX dgvData;
        private Label lblCLmbzl;
        private Label lblCLrlname;
        private Panel panel9;
        private Panel panel10;
        private Label label13;
        private Label lblCLyc;
        private Label lblCLdh;
        private Panel panel11;
        private Label lblCLcheng;
        private Label label16;
        private Panel panel12;
        private ProgressBar pBarCL;
        private Label lblCLzl;
        private Label lblCLwc;
        private Label lblCLwd;
        private Label label2;
        private Label lblCLmcpz;
        private Label lblBB;
        private Label lblExit;
        private Label txtLDH;
        private Label label4;
        private LblTxt txtKZ;
        private LblTxt txtDJ;
        private LblTxt txtMS;
        private Label label6;
        private Label label8;
        private LblTxt txtZL;
        private LblTxt txtSL;
        private LblTxt txtJH;
        private LblTxt txtYS;
        private LblTxt txtSH;
        private LblTxt txtSZ;
        private LblTxt txtKH;
        private LblTxt txtDDH;
        private Label label5;
        private Label label3;
        private Label lblKeyS;
        private Label lblTPerr;
        private DataGridView dgvDH;
        private DataGridViewTextBoxColumn col1;
        private DataGridViewTextBoxColumn col2;
        private DataGridViewTextBoxColumn col3;
        private DataGridViewTextBoxColumn col4;
        private DataGridViewTextBoxColumn col5;
        private DataGridViewTextBoxColumn col6;
        private DataGridViewTextBoxColumn col7;
        private DataGridViewTextBoxColumn col8;
        private DataGridViewTextBoxColumn colBH;
        private DataGridViewTextBoxColumn colGX;
        private DataGridViewTextBoxColumn colRL;
        private DataGridViewTextBoxColumn colYL;
        private DataGridViewTextBoxColumn colDW;
        private DataGridViewTextBoxColumn colCL;
        private DataGridViewTextBoxColumn colCLDW;
        private DataGridViewTextBoxColumn colDH;
        private DataGridViewTextBoxColumn colSN;
    }
}